name: Elm-CI

on: [ push, pull_request]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jorelali/setup-elm@v3
        with:
          elm-version: 0.19.1
      - name: Build the front-end
        working-directory: ./src/collector/elm-frontend
        run: elm make src/Main.elm
